version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  backend:
    image: ${image}
    network_mode: "host"
    container_name: test-task-backend-container
    ports:
      - 8070:8070
    depends_on:
      - postgres
    command: sh -c ./docker-compose-wait/wait
    environment:
      WAIT_HOSTS: postgres:5432